FROM apache/hive:3.1.3

USER root

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget -O /opt/hive/lib/postgresql-42.7.7.jar \
    https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.7/postgresql-42.7.7.jar && \
    chmod 644 /opt/hive/lib/postgresql-42.7.7.jar

RUN  wget -O /opt/hive/lib/hadoop-aws-3.1.1.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.1.1/hadoop-aws-3.1.1.jar && \
    wget -O /opt/hive/lib/aws-java-sdk-bundle-1.11.375.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.375/aws-java-sdk-bundle-1.11.375.jar && \
    chmod 644 /opt/hive/lib/hadoop-aws-3.1.1.jar && \
    chmod 644 /opt/hive/lib/aws-java-sdk-bundle-1.11.375.jar

# Add Iceberg Hive runtime
RUN wget -O /opt/hive/lib/iceberg-hive-runtime-1.7.2.jar \
    https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-hive-runtime/1.7.2/iceberg-hive-runtime-1.7.2.jar && \
    chmod 644 /opt/hive/lib/iceberg-hive-runtime-1.7.2.jar

# Add Delta Lake support for Hive Metastore
RUN wget -O /opt/hive/lib/delta-hive_2.13-3.3.2.jar \
    https://repo1.maven.org/maven2/io/delta/delta-hive_2.13/3.3.2/delta-hive_2.13-3.3.2.jar && \
    wget -O /opt/hive/lib/delta-standalone_2.13-3.3.2.jar \
    https://repo1.maven.org/maven2/io/delta/delta-standalone_2.13/3.3.2/delta-standalone_2.13-3.3.2.jar && \
    chmod 644 /opt/hive/lib/delta-hive_2.13-3.3.2.jar && \
    chmod 644 /opt/hive/lib/delta-standalone_2.13-3.3.2.jar

USER hive